### ISSUE TITLE
Group7 Todo Items

### ISSUE THREAD

**Issue by kiettiet** [miaonagemide/Group7#1]
- [x] Setup git repo
- [x] write helloworld
- [x] add all names to hello world
- [x] create a branch for the hello world gui application called "iteration0"
- [x] convert hello world to a GUI application
- [x] re-add all the names to the GUI app
- [x] Merge the interation0 branch
